### ISSUE TITLE
Insert a delay

### ISSUE THREAD

**Issue by frankrehfeld** [grandchild/autohidewibox#1]
Maybe it is possible to use a delay before hiding/showing the wibox. So it isn't shown everytime I'm switching the tag.

**Comment by grandchild** [comment]
Cool idea, I'll do it. :)

**Comment by grandchild** [comment]
I use

```
delayShow=850
delayHide=0
```

in my config at the moment.

**Comment by grandchild** [comment]
There is an occasional bug, that makes the wibox stay visible after rapid switching. I am aware of this, it doesn't happen often, but I don't know what the cause is yet.
